# -----------------------------------------------------
# General workspace rules
# name: "Custom"
# -----------------------------------------------------

workspace = 4, layout:monocle
workspace = special:special, defaultName:S
