# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = rounding 0, match:fullscreen 1
windowrule = no_blur 1, match:initial_class .*
windowrule = border_size 3, match:pin 1

# tag
windowrule = tag +game, match:initial_class HeavenBurnsRed|Hollow Knight Silksong|KingdomTwoCrowns|Minecraft.*|steam_app_.*
windowrule = tag +game, match:initial_title Terraria.*
windowrule = tag +game, match:xdg_tag proton-game
windowrule = tag +game_launcher, match:initial_class org.prismlauncher.PrismLauncher|steam
windowrule = tag +game_launcher, match:initial_class steam_app_.*, match:initial_title \s*
windowrule = tag +game_launcher, match:initial_title HBR_EN_Gamelauncher
windowrule = tag -game, match:tag game_launcher
windowrule = tag +social, match:initial_class ArmCord|WebCord|com.discordapp.Discord|discord|vesktop

# workspace rules
windowrule = workspace 2, match:tag social

windowrule = workspace 3, match:tag game_launcher

windowrule = workspace 4, match:tag game
windowrule = fullscreen_state 1 2, match:tag game
windowrule = monitor 0, match:tag game

windowrule = workspace special, match:initial_class YouTube Music

# effect rules
windowrule = float true,match:initial_class steam,match:initial_title Friends List # Steam Friends List
windowrule = float true,match:initial_class steam,match:initial_title Steam Settings # Steam Settings

windowrule = idle_inhibit fullscreen true, match:initial_class .*(celluloid|mpv|vlc).*
windowrule = idle_inhibit fullscreen true, match:initial_class .*[Ss]potify.*
windowrule = idle_inhibit fullscreen true, match:initial_class .*(LibreWolf|floorp|brave-browser|firefox|chromium|zen|vivaldi).*

windowrule = no_initial_focus 1, match:initial_class steam

windowrule = render_unfocused 1, match:initial_class HeavenBurnsRed

# Picture-in-Picture
windowrule {
    name = hyde_picture_in_picture
    match:title = [Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture.*
    tag = +picture-in-picture
    tag = +hyde_picture_in_picture
    float = true
    keep_aspect_ratio = true
    move = (monitor_w*0.73) (monitor_h*0.72)
    size = (monitor_w*0.25) (monitor_h*0.25)
    pin = true
}

windowrule = opacity 0.98 $& 0.98 $& 0.98,match:initial_class .*
windowrule = opacity 1.00 $& 1.00 $& 1.00,match:initial_class kitty
windowrule = opacity 1.00 $& 1.00 $& 1.00,match:tag game
windowrule = opacity 0.95 $& 0.95 $& 0.95,match:tag social
